baseURL = "https://ubuntusecuritypodcast.org/"
languageCode = "en-us"
title = "Ubuntu Security Podcast"
theme = "castanet"
googleAnalytics = "UA-123895434-1"

[params]
site_theme = "ubuntu"
site_layout = "row"
enable_jumbo = "true"
about_logo = "/img/usp_logo_250.png"
favicon = "/img/usp_logo_32.png"
copyright_notice = "Copyright 2020 [Canonical](https://www.canonical.com/)"
itunes_subscribe = "https://itunes.apple.com/au/podcast/ubuntu-security-podcast/id1429360004"
android_subscribe = "https://www.google.com/podcasts?feed=aHR0cHM6Ly91YnVudHVzZWN1cml0eXBvZGNhc3Qub3JnL2VwaXNvZGUvaW5kZXgueG1s"
#android_subscribe = "https://subscribeonandroid.com/ubuntusecuritypodcast.org/episode/index.xml"
spotify_subscribe = "https://open.spotify.com/show/0g0Kh2gQWP17Y6yye9bhkZ"
pocketcasts_subscribe = "https://pca.st/O9Df"
description = "A weekly podcast talking about the latest developments and updates from the Ubuntu Security team."
media_prefix = "https://people.canonical.com/~amurray/USP/"


[params.feed]
copyright = "Copyright 2020 Canonical"
itunes_author = "Ubuntu Security Team"
itunes_summary = "A weekly podcast talking about the latest developments and updates from the Ubuntu Security team, including a summary of the security vulnerabilities and fixes from the last week as well as a discussion on some of the goings on in the wider Ubuntu Security community."
itunes_owner_name = "Alex Murray"
itunes_owner_email = "alex.murray@canonical.com"
itunes_image = "https://ubuntusecuritypodcast.org/img/usp_logo_1400.png"
itunes_top_category = "Technology"
explicit = "no"

[params.social]
twitter = "ubuntu_sec"
twitter_domain = "ubuntu.com"

[params.authors]
[params.authors.Alex]
name = "Alex Murray"
thumbnail = "https://avatars3.githubusercontent.com/u/56540?s=100&v=4"
bio = "Ubuntu Security Tech Lead at Canonical"
github = "alexmurray"
twitter = "alex_murray"
[params.authors.Joe]
name = "Joe McManus"
thumbnail = "https://avatars1.githubusercontent.com/u/8714436?s=100&v=4"
bio = "Ubuntu Security Director at Canonical"
github = "joemcmanus"
twitter = "joeubuntu"

[permalinks]
        page = "/:filename/"
        about = "/:filename/"
        contact = "/:filename/"
        episode = "/:filename/"

[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about/"
[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact/"
